### ISSUE TITLE
Getting it to run

### ISSUE THREAD

**Issue by dbrgn** [japaric/photon#9]
I'm trying to get your example to run.

Steps taken so far:

``` toml
# Cargo.toml
[package]
name = "blinky"
version = "0.1.0"
authors = ["Danilo <...>"]

[dependencies]
photon = { git = "https://github.com/japaric/photon" }
```

``` rust
// src/main.rs
#![no_std]
extern crate photon;

use photon::{Pin, PinMode, PinState};

#[no_mangle]
pub fn setup() {
    photon::pin_mode(Pin::D7, PinMode::Output)
}

#[no_mangle]
#[export_name = "loop"]
pub fn loopy() {
    photon::digital_write(Pin::D7, PinState::Low);
    photon::delay(250);
    photon::digital_write(Pin::D7, PinState::High);
    photon::delay(250);
}

fn main() { }
```

Then I ran `cargo install xargo && xargo build --release`.

During the compilation process, I'm getting the following error:

```
--- stderr
Cloning into '/tmp/photon.Nd9Xg0tte6Re'...
In file included from ./src/photon/wiced/network/LwIP/WWD/FreeRTOS/arch/cc.h:69:0,
                 from ./src/photon/wiced/network/LwIP/ver1.4.0.rc1/src/include/lwip/arch.h:43,
                 from ./src/photon/wiced/network/LwIP/ver1.4.0.rc1/src/include/lwip/debug.h:35,
                 from ./src/photon/wiced/network/LwIP/ver1.4.0.rc1/src/include/lwip/opt.h:46,
                 from ./src/photon/wiced/network/LwIP/ver1.4.0.rc1/src/include/ipv4/lwip/ip_addr.h:35,
                 from ./src/photon/wiced/network/LwIP/WICED/wiced_network.h:43,
                 from ./src/photon/include/wiced_tcpip.h:44,
                 from ./src/photon/include/wiced.h:46,
                 from src/photon/delay_hal.c:27:
./src/photon/wiced/network/LwIP/WWD/FreeRTOS/cpu.h:43:0: error: "BYTE_ORDER" redefined [-Werror]
 #define BYTE_ORDER LITTLE_ENDIAN

In file included from /usr/arm-none-eabi/include/sys/types.h:67:0,
                 from /usr/arm-none-eabi/include/stdio.h:48,
                 from ./src/photon/wiced/WWD/include/wwd_debug.h:40,
                 from ./src/photon/wiced/WWD/include/wwd_assert.h:42,
                 from ./src/photon/wiced/RTOS/FreeRTOS/WWD/ARM_CM3/FreeRTOSConfig.h:41,
                 from ./src/photon/wiced/RTOS/FreeRTOS/ver7.5.2/Source/include/FreeRTOS.h:78,
                 from ./src/photon/wiced/RTOS/FreeRTOS/WWD/wwd_rtos.h:46,
                 from ./src/photon/wiced/WWD/include/RTOS/wwd_rtos_interface.h:47,
                 from ./src/photon/wiced/platform/MCU/STM32F2xx/peripherals/platform_mcu_peripheral.h:56,
                 from ./src/photon/wiced/platform/include/platform_peripheral.h:42,
                 from ./src/photon/include/wiced_platform.h:46,
                 from ./src/photon/include/wiced.h:44,
                 from src/photon/delay_hal.c:27:
/usr/arm-none-eabi/include/machine/endian.h:20:0: note: this is the location of the previous definition
 #define BYTE_ORDER _BYTE_ORDER

cc1: all warnings being treated as errors
make[1]: *** [../build/module.mk:218: ../build/target/hal/platform-6/./src/photon/delay_hal.o] Error 1
make: *** [build/recurse.mk:12: hal] Error 2
thread '<main>' panicked at 'assertion failed: try!(Command:: new ( "make" ) . current_dir ( td ) . env_remove ( "TARGET" ) .
     env ( "PLATFORM" , "photon" ) . status (  )).success()', /home/danilo/.cargo/git/checkouts/photon-ab8b7f25d5ae18d8/master/build.rs:48
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Seems like a conflict of constants between FreeRTOS and that `endian.h` file?

**Comment by dbrgn** [comment]
Hm. That was on my local system (Arch Linux). In Docker it seems to compile (but `Pin` etc don't seem to exist yet). Any idea what the problem could be? I'd prefer to work without the container.

**Comment by japaric** [comment]
> [dependencies]
> photon = { git = "https://github.com/japaric/photon" }

This doesn't work right now. You have to build your apps in this Cargo project under src/bin or src/examples.

> Seems like a conflict of constants between FreeRTOS and that endian.h file?

What arm-none-eabi-gcc package are you using? The Arch Linux one? You have to use the arm-none-eabi-gcc from the [gcc-arm-embedded](https://launchpad.net/gcc-arm-embedded), other version don't work AFAIK. This is [a requirement of the spark/firmware](https://github.com/spark/firmware/blob/develop/docs/dependencies.md#1-gcc-for-arm-cortex-processors) project.

> but Pin etc don't seem to exist yet

The README got outdated. Check the "apps" in the src/bin directory. I have moved the HAL, which is now autogenerated, to the particle-hal crate.

**Comment by incendiary-ca** [comment]
This is a bit old, but I ran into the same issue today, so I'll post what I found in case it helps others...

I'm running Ubuntu 16.04, and the latest package for gcc-arm-embedded installs arm-none-eabi-gcc v5.4 ... downgrading to 5.3 resolves this issue, and then the build goes off without a hitch.

For Ubuntu, this meant removing the gcc-arm-embedded package, downloading the 5.3 tar.bz2, untarring/unzipping it, and setting a path to the bin folder at the root of where you untarred the file.

**Comment by japaric** [comment]
This repo has been update. Check [photon-quickstart](https://github.com/japaric/photon-quickstart) for updated instructions.

**Comment by dbrgn** [comment]
@japaric you are awesome! :) blinky works perfectly on my photon.
